# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "npm install",
    "cd client && npm install",
    "cd ../server && npm install", 
    "cd ../admin && npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
